# need to update for node js


# name: Package and Deploy
# on: [push]
# jobs:
#   package:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v1

#       - name: Set up JDK 18
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.18

#       - name: Gradle Build
#         run: ./gradlew build --stacktrace --info
#         env:
#           HOSTNAME: localhost
#           JWT_SECRET: asdfasdf
#           AWS_ACCESS_KEY_ID: asdf
#           AWS_SECRET_ACCESS_KEY: asdf
#           DB_DOMAIN: localhost
#           DB_USERNAME: postgres
#           DB_DATABASE: eil_db_1
#           DB_PASSWORD: asdfasdf
#           S3_URL_PREFIX: asdf
#           KAFKA_BOOTSTRAP: "localhost:8107"

#       - name: Gradle Package BootJar
#         run: ./gradlew bootJar

#       - name: Dockerize
#         run: docker build -t etenlab/database-api .

#       - name: Log in to Docker Hub
#         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with:
#           images: etenlab/database-api
      
#       - name: Build and push Docker image
#         uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#         with:
#           context: .
#           push: true
#           tags: etenlab/database-api:latest
#           labels: ${{ steps.meta.outputs.labels }}
